FROM node:24-alpine AS builder
WORKDIR /app
COPY package*.json tsconfig*.json ./
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
COPY src ./src
COPY vite.config.ts index.html public ./

RUN npm ci
RUN npm run build  

FROM nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80