name: CI

on:
  push:
    branches: [ main ]

jobs:
  lint-and-format-front:
    defaults:
      run:
        working-directory: front
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.2.0
    - name: Install deps
      run: npm i
    - name: Check format
      run: npm run format:check 
    - name: Check lint
      run: npn run lint:check
  lint-and-format-back:
    defaults:
      run:
        working-directory: back
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.2.0
    - name: Install deps
      run: npm i
    - name: Check format
      run: npm run format:check 
    - name: Check lint
      run: npn run lint:check