name: CI

on:
  push:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.2.0
    - name: Install deps
      run: npm i
    - name: Check front
      run: cd front && npm run format:check && npn run lint:check
    - name: Check back
      run: cd back && npm run format:check && npn run lint:check